

services:
  weaviate:
    image: semitechnologies/weaviate:1.20.3
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./weaviate_data"
      ENABLE_MODULES: ""
      CLUSTER_HOSTNAME: "node1"
      

  app:
    build: .
    container_name: transcript_bot
    restart: always
    depends_on:
      - weaviate
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-4o-mini
      OPENAI_EMBED_MODEL: text-embedding-3-small
      WEAVIATE_URL: http://weaviate:8080
      WEAVIATE_CLASS_NAME: Transcript
      PYTHONPATH: /app
