version: "3.9"
services:
  weaviate:
    image: semitechnologies/weaviate:1.20.3
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    command:
      --host 0.0.0.0
      --port 8080
      --scheme http

  app:
    build: .
    container_name: chatbot_app
    restart: always
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    command: python src/main.py
